# This is a basic workflow to help you get started with Actions

name: gh_pages-sitemap-ping

on:
  page_build:
  workflow_dispatch:
  
jobs:
  gh_pages-sitemap-ping:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: ping
        env:
          MAP_URL: "NULL" # set custom URL if you use it
        run: |
          if [ "NULL" = "${MAP_URL}" ]; then
            if [ -s CNAME ]; then
              MAP_URL="$(cat CNAME)"
            else
              MAP_URL="$(echo ${{ github.repository }} | sed -e "s/^.*${{ github.github.repository_owner }}\///")"
            fi
              MAP_URL="https://${MAP_URL}/sitemap.xml"
          fi

          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &
          curl -v "http://www.bing.com/ping?sitemap=${MAP_URL}" &
          wait
          echo "Done"
