# This is a basic workflow to help you get started with Actions

name: gh_pages-sitemap-ping

on:
  page_build:
  workflow_dispatch:
  
jobs:
  gh_pages-sitemap-ping:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: ping
        env:
          MAP_URL: "NULL" # set custom URL if you use it
        run: |
          BASE_URL="https://www.coelacanth-dream.com"
          MAP_URL="${BASE_URL}/sitemap.xml"
          RSS_URL="${BASE_URL}/posts/index.xml"

          sleep 3
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          curl -v "http://www.google.com/ping?sitemap=${MAP_URL}" &> /dev/null &
          curl -v "http://www.bing.com/ping?sitemap=${RSS_URL}" &> /dev/null &
          wait
          echo "Done"
