# This is a basic workflow to help you get started with Actions
name: ping

on:
  page_build:
  workflow_dispatch:

jobs:
  gh_pages-sitemap-ping:
    runs-on: ubuntu-18.04
    steps:
      - name: "ping"
        uses: Umio-Yasuno/gh_pages-sitemap-ping@v0.2
